language: java

jdk:
  - oraclejdk8

dist: trusty

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - "$HOME/.m2/"

env:
  global:
    - PATH=$PATH:${HOME}/google-cloud-sdk/bin
    # CI_DEPLOY_USERNAME
    - secure: juDdrb0JmYWTiGT9w4/aDk6oufgz2s3ZnEBsWHYWeR8Chhl+FFL1rtseFd6MANk7NStbtzZzGRZDVRWW6VLYqiVJccbMaj+DoryE8SCYVViO1BecqCGnQdlMu+PkM0HSwbt/No7/6BNbijLENOyMOCDTV++X0lKFA5hZPwj01sj4HS5wqqgLP07D2qQdLTilyF4A9kasVfWPqfy6GZD0URZ+y2fHAQKc9dXtzEXUVOGKIQjo26rl4wnxXSL+eKZ7V38bofOR4FS/JKnJr0iHB4LXTZqGUwgYKVR/aCsgTcEX1512bINeEQL9jUzPu6h0Lw4LdiDVvQpmKhQ303MW+Wwmlg0ixbeFcjQEp6oyItBOpaIKCHBzxdv/23hFECAUIJYB1QQNam7wmVxrsoFTtW7W0dm+uC/Z7f3auvyh3ow6Y1yISY9AJqaEOlbf0GeOJDO2QEtk3SOVa74kE6Rmoqpz1LEcZ6xSNAhTPDs9Lwg8nk0kQANB9ABhNCxiHf0kFBKXvVs9R6JKcQFZwTj/ZqVSNCAfrxxSDbZNH52oSM3SQCh0kQmAn9ExVLT3bQnh1KUG7u+ux6G+O24b3EHJk8EF9RIUsjCtfOOXK8z3ceXpTmBfdYymdLdFvHPrlK4eKD33sHpJPl0L3ybo8VoGQDG14MxMCdtuCECJjiCMkC8=
    # CI_DEPLOY_PASSWORD
    - secure: QZQcY3lk/jy82ujeddZoXdPdhitx/xxOzI8fl32w0svuNBdVl+Pja9srS6pDZPJWyWzIOCfQ8fAF7crt+eWaJzqjBdqp+Vfl6QvNR08vkMGdVtpWc+F8l3MIjbYCWofeyuQTUx78h8JTafeW/S6yp0hKu5dEJ41yzkup4aEwsW+yErN7y3qo4+Z+1c1hcbZY5mayhLcReTCdQfZnzn77ianCQ4Nz+wQdtGI/JhhTgLoX29joS5PieCujlZu0v3BVNrDvhp8eEh7aXiouczUZ2rovNHYR/yI4yr3sQmSFbJjXkeHAI0XFvQOk2HQ9uzTbnEfHN4+CAAvaSU9IJ/+2JnZM1MT2TW46bEcnLCowLDcaUN/6X4+LcnnDXbQoLDFRrtrkkJTeKuLy1df6cTwSniW1QY67WVZsOcQLavfwZ/noKTk7D9Wal9sYkiiKIUywbZ0CMMSnlhdeuqQEM0xPMSjWcgxLY75gxKx+xpd5aZtJzj7hnL8LzM8O5YhERgQ7ck2YG8jK09+0Qz073qjiZtJoIbmRYAiRnRnZlIAQA6PKGp2fApprMRyESGH7CsCUAtvMgNI6alpPZw3a58zi9XYY7LDZrdib8pQ5uhr2BTDv1+bQ5/kAyRsG7frkctOi30aW9POhR8d6suIRHKxxfb1SQwNMvtG1szdRXaHSkzc=
    # GPG_KEY_NAME
    - secure: mphPvJXxJHcUXPDrOfoxz+wS67AOQa4DqL1cJtqq2D0Hw/+NqOZpP+AO4a+mVuDKPLxf33XPZUDK5w4MZJSygJL0wXPd2S0x4w/9K9SQWuEfBVXXJDLokudXjOZTcYCJ9W5wtVC38xvRankfK2KSPIaW8zwVUaNqZHuAohzg3V5U9yUvlUZigvkm2Quslt8zAHmjY/2aIBhLTkqAha2vsscBobgHL0efxA7GG/h/wDWRDz55ssBOBJt/2kRjqjJVsTi3zoasZcrotQA1J76wFboj5J6G2CJBRMLQoDCJPQROqhtCWCLPI7ZD1uKBcf+5sFCMMOV8NnhKQo2kuDxp98k6hy6bB4c/fH1E/Xf1cP4JMUvZzBTGUj4W8eDs7GQJksI0kSUzRqQ4tJXCuqCmQisjSHAyTl52PTMo64RPjsdVEX9bvqieDgwdiBOKe2vXY0ck/Xg524wakaD7jU5582dpfjRWH+BTHTHr6W167I0Ua4Qa4VhC2hTP6b9A6Wyaqq13dpC/Yz+pPX0/+mQJShDAxwIeCE0Sd3PLUfBqLMmBbuViYW38CbWg7sSupuFAlAwTrW+gQvgY/ypWQZekyU6dNgxZNa665FRnhmEcRyJiLjF+7VX0Iopa8egGtJCejbd4Qj8fIHIIO1dC6XNJQJcjSCwicJwYWPJ9ba3BvWE=
    # GPG_PASSPHRASE
    - secure: QyqTxtD5VrzSSKFx4gRuhJPb18PIvFg87WP/BJegWaoBtQIrrA/+aWqkw74x+a9Fx8pXbkLq7pEB9M/nNr3Dym0/edGETCJ/MPtYth4QJUredp4g3SDPaCGTpvKyKzON5XyrZ44pwzuPbYACa5NRcoaEIyl3uYR7uonq4kJx+xFDo7SYO8gZq3Vw5owe8tel0GHzpCQl6hjvtd+A6T176JUx8IMgNhq9jJrEZ9sKgTTZGFRMxbU7iyNaTsVYfkDlHhV0h/0ZDT+LPU/jj+bnB3S4UpaHqbRSIv5MgWQYb/mwiE38lZuNtYL66b+MtKh6m8QbGAIuX32ST3RF9+tB19YvGcuujq1uK4bykjxCGMDgQlK0v+kV3PZYzucOoS7YWdIVEXcuTo6HNVNYX4T3WinlNcyhMKKY3L7k3fywfwRRgl/d0VHmOsYDc+XamNkFZYKGjYab3ISn3LmV12nDEZBib/ScM2nN28ycKHSJCYl/g2QR6y9gOIuUzR1HTCPQwPx2pkEknWZdJFsx97HKVqogjAWf0Z7JhPOrT5UeNEGbDl8Xmod/PKNIlomsHbrTy5S4IMJu2IBsQzPjqxdEZltAawO76iOyL2JU0hIlA3OfluIG2FCfegC3a9AFlQCfu53dg207oxQVvTuFPN+WaZ3Frzt+VdjDD9U42ZowTVI=

before_install:
  # Decrypt the secrets (only non pull-requests)
  - export CREDENTIALS_STORE=$(mktemp -d)
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in travis_files/secrets.tar.enc -out travis_files/secrets.tar -d; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then tar xvf travis_files/secrets.tar --directory $CREDENTIALS_STORE; fi
  # Import the FOSS signing key
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then gpg --fast-import ${CREDENTIALS_STORE}/spydra_sign_keys; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export GOOGLE_APPLICATION_CREDENTIALS=${CREDENTIALS_STORE}/spydra_foss_ci.json; fi
  # If the SDK is not already cached, download it and install it into path
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components install --quiet beta || true
  - gcloud version
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS; fi

branches:
  only:
  - master

# Skipping the install step as the script step will do all we need.
install: true

script:
  # Run on pull requests (encrypted data not available for pull requests)
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn clean verify; fi'
  # Run on merges to master
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn deploy -P release,install-init-scripts --settings=travis_files/settings.xml; fi'

notifications:
  email: false
