language: java

jdk:
  - oraclejdk8

dist: trusty

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - "$HOME/.m2/"

env:
  global:
    - PATH=$PATH:${HOME}/google-cloud-sdk/bin
    # CI_DEPLOY_USERNAME
    - secure: cIvKGNiNStLgdtoJ7O63u5Ln7nGbQRuMDDx9RYpCEgWxhlY01uE/aviyFizzuUJEgeCeKDmqeL8xwjGNsPjC5ufJ9TSIUVjRwfDKqTexe7ONNefzkiYUTfIUd5GZB/uhkDhR9CPIDb1a6yLqnT7UMu5LMqEsBVKhSQIEkfxE2yhyr1KTUKffEsjTEaxmWrU4OHeJpG9wY+jIdFFfew8wlTsLcNHbk1UjHErZYcQDif5MVLZ/l8DzS9X7s/GuGmwybk20vzy6tIlNgaVw/XM2END/9cyh7EQJnN0dxTAQFUkxKh6LzlpGQB4naU/Qw5sNzcRz3WSsJt92C3ywZd68VVZC3Rb41EPcpu+FN+ud/a5EB8rO5g9c2p+2Jdh+gRaxUVOO4EDL1GrTSR2mwnvnsJleUYjHeRimpBCNuUXOHNIK95E2vVZ9AZGOVsjqD+g11H8yu2Fe9v+UKVBAI2zb23j/IeYZJ6+oFw9rNaa0lQdgj5Twopk91OoTWFJ4Dn+DOoZ16no3fyVmVPmXkwT2YfwUxOiAUyFeWWGfMdlFdYQj1EfPY99ZLU4N2GsqArNwCaZi+MAOOlcQc8s0v6X+hjtfcraUof3TrvhqXLTNgs2a+yMMGaqqomoTgvNHm2zYURhofYUIR/FBJ9/RsEX/9/YTWoJxl8w9dfGPwFCk0wg=
    # CI_DEPLOY_PASSWORD
    - secure: hfqiDX2TqEp9zRmWJkoIeJnqY6AKL37ZGBiuCUe3Xl2hf9Eyu6W0EsZFjA04Uw+LsBqCwpwc0mDRMhtmm4ZzfVMe3OwJZ0x0g6H8LMTh2oSWa5MYG9DVy4dZZAWlErLyNVAzrZpMMMH67I2JD8p2pT7H0fGHD/gpotECNgovMD1omAXW1UEk8rdRUd4xqLSThetCdZEW7glP/2jVRXWFodlPUGOs/UCJu4R0rDz7KOqN44AMmW277SMLzIIWspRyo6CDVwAqxftLNCOYSZFZWGvGqnShFFb/ZWAOGXxFy2UCpxeXIv2OPkVlArhVzyOA8aVVgm1m5Y6/rsX3W1R/PBhB+X/KAeiSsfmV7VRbSS+nowRsnGicQAT6lwCOIQ4YLqMvcLfpfK+5qN6q04ccT4PiD88b1oNAX3fXeLKGpq1MJJowJZdn8m2bHBwtuCNca4rfFbIQ1sCgQZWoZPrFbnAcZldFFqX1jy83A5D0XnhARUIeQ6Aa7w0srlutB6XvXSh9Truc0SzDOfDH72Kyjo6PlAmHSao8UmHteg5oXsFflQ24flBnm87rOkctsLTam/rakvoisCY5GVWddtd2iMOnMJj1zcNE1iqpWcKqWZu8mTDp/HDtQMf/S6SshWcLM1mlbr/V7Va+nx33cybkLq2TAbnaNGOwdFUmvaRHmS4=
    # GPG_KEY_NAME
    - secure: mphPvJXxJHcUXPDrOfoxz+wS67AOQa4DqL1cJtqq2D0Hw/+NqOZpP+AO4a+mVuDKPLxf33XPZUDK5w4MZJSygJL0wXPd2S0x4w/9K9SQWuEfBVXXJDLokudXjOZTcYCJ9W5wtVC38xvRankfK2KSPIaW8zwVUaNqZHuAohzg3V5U9yUvlUZigvkm2Quslt8zAHmjY/2aIBhLTkqAha2vsscBobgHL0efxA7GG/h/wDWRDz55ssBOBJt/2kRjqjJVsTi3zoasZcrotQA1J76wFboj5J6G2CJBRMLQoDCJPQROqhtCWCLPI7ZD1uKBcf+5sFCMMOV8NnhKQo2kuDxp98k6hy6bB4c/fH1E/Xf1cP4JMUvZzBTGUj4W8eDs7GQJksI0kSUzRqQ4tJXCuqCmQisjSHAyTl52PTMo64RPjsdVEX9bvqieDgwdiBOKe2vXY0ck/Xg524wakaD7jU5582dpfjRWH+BTHTHr6W167I0Ua4Qa4VhC2hTP6b9A6Wyaqq13dpC/Yz+pPX0/+mQJShDAxwIeCE0Sd3PLUfBqLMmBbuViYW38CbWg7sSupuFAlAwTrW+gQvgY/ypWQZekyU6dNgxZNa665FRnhmEcRyJiLjF+7VX0Iopa8egGtJCejbd4Qj8fIHIIO1dC6XNJQJcjSCwicJwYWPJ9ba3BvWE=
    # GPG_PASSPHRASE
    - secure: QyqTxtD5VrzSSKFx4gRuhJPb18PIvFg87WP/BJegWaoBtQIrrA/+aWqkw74x+a9Fx8pXbkLq7pEB9M/nNr3Dym0/edGETCJ/MPtYth4QJUredp4g3SDPaCGTpvKyKzON5XyrZ44pwzuPbYACa5NRcoaEIyl3uYR7uonq4kJx+xFDo7SYO8gZq3Vw5owe8tel0GHzpCQl6hjvtd+A6T176JUx8IMgNhq9jJrEZ9sKgTTZGFRMxbU7iyNaTsVYfkDlHhV0h/0ZDT+LPU/jj+bnB3S4UpaHqbRSIv5MgWQYb/mwiE38lZuNtYL66b+MtKh6m8QbGAIuX32ST3RF9+tB19YvGcuujq1uK4bykjxCGMDgQlK0v+kV3PZYzucOoS7YWdIVEXcuTo6HNVNYX4T3WinlNcyhMKKY3L7k3fywfwRRgl/d0VHmOsYDc+XamNkFZYKGjYab3ISn3LmV12nDEZBib/ScM2nN28ycKHSJCYl/g2QR6y9gOIuUzR1HTCPQwPx2pkEknWZdJFsx97HKVqogjAWf0Z7JhPOrT5UeNEGbDl8Xmod/PKNIlomsHbrTy5S4IMJu2IBsQzPjqxdEZltAawO76iOyL2JU0hIlA3OfluIG2FCfegC3a9AFlQCfu53dg207oxQVvTuFPN+WaZ3Frzt+VdjDD9U42ZowTVI=

before_install:
  # Decrypt the secrets (only non pull-requests)
  - export CREDENTIALS_STORE=$(mktemp -d)
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in travis_files/secrets.tar.enc -out travis_files/secrets.tar -d; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then tar xvf travis_files/secrets.tar --directory $CREDENTIALS_STORE; fi
  # Import the FOSS signing key
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then gpg --fast-import ${CREDENTIALS_STORE}/spydra_sign_keys; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export GOOGLE_APPLICATION_CREDENTIALS=${CREDENTIALS_STORE}/spydra_foss_ci.json; fi
  # If the SDK is not already cached, download it and install it into path
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components install --quiet beta || true
  - gcloud version
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS; fi

branches:
  only:
  - master

# Skipping the install step as the script step will do all we need.
install: true

script:
  # Run on pull requests (encrypted data not available for pull requests)
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn clean verify; fi'
  # Run on merges to master
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn deploy -P release,install-init-scripts --settings=travis_files/settings.xml; fi'

notifications:
  email: false
